/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BlueprintExecutionGeneration,
  BlueprintExecutionGeneration$inboundSchema,
} from "./blueprintexecutiongeneration.js";

/**
 * An edge containing a Blueprint Execution Generation node
 */
export type BlueprintExecutionGenerationEdge = {
  /**
   * An opaque cursor used for pagination
   */
  cursor: string;
  /**
   * Represents a single generation within a Blueprint Execution
   */
  node: BlueprintExecutionGeneration;
};

/** @internal */
export const BlueprintExecutionGenerationEdge$inboundSchema: z.ZodType<
  BlueprintExecutionGenerationEdge,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string(),
  node: BlueprintExecutionGeneration$inboundSchema,
});

export function blueprintExecutionGenerationEdgeFromJSON(
  jsonString: string,
): SafeParseResult<BlueprintExecutionGenerationEdge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BlueprintExecutionGenerationEdge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BlueprintExecutionGenerationEdge' from JSON`,
  );
}
