/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BlueprintExecutionStatus,
  BlueprintExecutionStatus$inboundSchema,
} from "./blueprintexecutionstatus.js";
import { NodeInput, NodeInput$inboundSchema } from "./nodeinput.js";

/**
 * Represents the Execution of a Blueprint Version
 */
export type BlueprintExecution = {
  akUUID: string;
  createdAt: string;
  /**
   * Inputs of the Blueprint Execution
   */
  inputs: Array<NodeInput>;
  public: boolean;
  /**
   * The status of a Blueprint Execution.
   */
  status: BlueprintExecutionStatus;
};

/** @internal */
export const BlueprintExecution$inboundSchema: z.ZodType<
  BlueprintExecution,
  z.ZodTypeDef,
  unknown
> = z.object({
  akUUID: z.string(),
  createdAt: z.string(),
  inputs: z.array(NodeInput$inboundSchema),
  public: z.boolean(),
  status: BlueprintExecutionStatus$inboundSchema,
});

export function blueprintExecutionFromJSON(
  jsonString: string,
): SafeParseResult<BlueprintExecution, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BlueprintExecution$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BlueprintExecution' from JSON`,
  );
}
