/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The status of a Blueprint Execution.
 */
export enum BlueprintExecutionStatus {
  Pending = "PENDING",
  Queued = "QUEUED",
  Completed = "COMPLETED",
  Failed = "FAILED",
}

/** @internal */
export const BlueprintExecutionStatus$inboundSchema: z.ZodNativeEnum<
  typeof BlueprintExecutionStatus
> = z.nativeEnum(BlueprintExecutionStatus);
