/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The status of a Blueprint Execution Generation
 */
export enum BlueprintExecutionGenerationStatus {
  Pending = "PENDING",
  Completed = "COMPLETED",
  Failed = "FAILED",
}

/** @internal */
export const BlueprintExecutionGenerationStatus$inboundSchema: z.ZodNativeEnum<
  typeof BlueprintExecutionGenerationStatus
> = z.nativeEnum(BlueprintExecutionGenerationStatus);
