/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of request for the Canvas Editor.
 */
export enum CanvasRequestType {
    Inpaint = "INPAINT",
    Outpaint = "OUTPAINT",
    Sketch2Img = "SKETCH2IMG",
    Img2Img = "IMG2IMG",
}

/** @internal */
export namespace CanvasRequestType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof CanvasRequestType> =
        z.nativeEnum(CanvasRequestType);
    export const outboundSchema: z.ZodNativeEnum<typeof CanvasRequestType> = inboundSchema;
}
