/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the current task.
 */
export enum JobStatus {
    Pending = "PENDING",
    Complete = "COMPLETE",
    Failed = "FAILED",
}

/** @internal */
export const JobStatus$: z.ZodNativeEnum<typeof JobStatus> = z.nativeEnum(JobStatus);
