/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The services to be chosen for calculating the API credit cost.
 */
export enum PricingCalculatorServices {
  ImageGeneration = "IMAGE_GENERATION",
  FantasyAvatarGeneration = "FANTASY_AVATAR_GENERATION",
  MotionSvdGeneration = "MOTION_SVD_GENERATION",
  MotionVideoGeneration = "MOTION_VIDEO_GENERATION",
  Veo3MotionVideoGeneration = "VEO3_MOTION_VIDEO_GENERATION",
  LcmGeneration = "LCM_GENERATION",
  ModelTraining = "MODEL_TRAINING",
  TextureGeneration = "TEXTURE_GENERATION",
  UniversalUpscaler = "UNIVERSAL_UPSCALER",
  UniversalUpscalerUltra = "UNIVERSAL_UPSCALER_ULTRA",
}

/** @internal */
export const PricingCalculatorServices$outboundSchema: z.ZodNativeEnum<
  typeof PricingCalculatorServices
> = z.nativeEnum(PricingCalculatorServices);
