/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The scheduler to generate images with. Defaults to EULER_DISCRETE if not specified.
 */
export enum SdGenerationSchedulers {
  Klms = "KLMS",
  EulerAncestralDiscrete = "EULER_ANCESTRAL_DISCRETE",
  EulerDiscrete = "EULER_DISCRETE",
  Ddim = "DDIM",
  DpmSolver = "DPM_SOLVER",
  Pndm = "PNDM",
  Leonardo = "LEONARDO",
}

/** @internal */
export const SdGenerationSchedulers$inboundSchema: z.ZodNativeEnum<
  typeof SdGenerationSchedulers
> = z.nativeEnum(SdGenerationSchedulers);
/** @internal */
export const SdGenerationSchedulers$outboundSchema: z.ZodNativeEnum<
  typeof SdGenerationSchedulers
> = SdGenerationSchedulers$inboundSchema;
