/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    bearerAuth: string;
};

/** @internal */
export namespace Security$ {
    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
        .object({
            bearerAuth: z.string(),
        })
        .transform((v) => {
            return {
                bearerAuth: v.bearerAuth,
            };
        });

    export type Outbound = {
        bearerAuth: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            bearerAuth: z.string(),
        })
        .transform((v) => {
            return {
                bearerAuth: v.bearerAuth,
            };
        });
}
