/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A text variable for replacing placeholders in Blueprint templates
 */
export type TextVariable = {
  /**
   * The name of the placeholder variable (without curly braces)
   */
  name: string;
  /**
   * The value to replace the placeholder with
   */
  value: string;
};

/** @internal */
export const TextVariable$inboundSchema: z.ZodType<
  TextVariable,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  value: z.string(),
});
/** @internal */
export type TextVariable$Outbound = {
  name: string;
  value: string;
};

/** @internal */
export const TextVariable$outboundSchema: z.ZodType<
  TextVariable$Outbound,
  z.ZodTypeDef,
  TextVariable
> = z.object({
  name: z.string(),
  value: z.string(),
});

export function textVariableToJSON(textVariable: TextVariable): string {
  return JSON.stringify(TextVariable$outboundSchema.parse(textVariable));
}
export function textVariableFromJSON(
  jsonString: string,
): SafeParseResult<TextVariable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextVariable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextVariable' from JSON`,
  );
}
