/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * The type of variation.
 */
export enum VARIATIONTYPEEnum {
  Outpaint = "OUTPAINT",
  Inpaint = "INPAINT",
  Upscale = "UPSCALE",
  Unzoom = "UNZOOM",
  Nobg = "NOBG",
}
