/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Query parameters are provided in the request body as a JSON object
 */
export class CreateVariationUpscaleRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}

export class CreateVariationUpscale200ApplicationJSONSDUpscaleJobOutput extends SpeakeasyBase {
    /**
     * API Credits Cost for Upscale Variation. Available for Production API Users
     */
    @SpeakeasyMetadata()
    @Expose({ name: "apiCreditCost" })
    apiCreditCost?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}

/**
 * Responses for POST /variations/upscale
 */
export class CreateVariationUpscale200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sdUpscaleJob" })
    @Type(() => CreateVariationUpscale200ApplicationJSONSDUpscaleJobOutput)
    sdUpscaleJob?: CreateVariationUpscale200ApplicationJSONSDUpscaleJobOutput;
}

export class CreateVariationUpscaleResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Responses for POST /variations/upscale
     */
    @SpeakeasyMetadata()
    createVariationUpscale200ApplicationJSONObject?: CreateVariationUpscale200ApplicationJSON;
}
