/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * The model to use for the video generation. Defaults to MOTION2 if not specified.
 */
export enum CreateTextToVideoGenerationString {
  Motion2 = "MOTION2",
  Veo3 = "VEO3",
}

/**
 * The resolution of the video. Defaults to RESOLUTION_480 if not specified. VEO3 only supports RESOLUTION_720 and RESOLUTION_1080.
 */
export enum CreateTextToVideoGenerationMotionString {
  Resolution480 = "RESOLUTION_480",
  Resolution720 = "RESOLUTION_720",
  Resolution1080 = "RESOLUTION_1080",
}

/**
 * Query parameters can also be provided in the request body as a JSON object
 */
export type CreateTextToVideoGenerationRequestBody = {
  /**
   * An array of elements/loras objects that will be applied sequentially to the output. Elements are only supported for Motion2.0 generations.
   */
  elements?: Array<shared.ElementInput> | null | undefined;
  /**
   * Smoothly blend frames for fluid video transitions using Interpolation.
   */
  frameInterpolation?: boolean | null | undefined;
  /**
   * Height of the output video.
   */
  height?: number | null | undefined;
  /**
   * Whether the generation is public or not
   */
  isPublic?: boolean | null | undefined;
  /**
   * The model to use for the video generation. Defaults to MOTION2 if not specified.
   */
  model?: CreateTextToVideoGenerationString | null | undefined;
  /**
   * The negative prompt used for the video generation.
   */
  negativePrompt?: string | null | undefined;
  /**
   * The prompt used to generate video
   */
  prompt: string;
  /**
   * Whether to enhance the prompt.
   */
  promptEnhance?: boolean | null | undefined;
  /**
   * A natural language instruction used to modify the main prompt. For example, 'make it cinematic', 'add a rainbow', or 'change the subject to a cat'.
   */
  promptEnhanceInstruction?: string | null | undefined;
  /**
   * The resolution of the video. Defaults to RESOLUTION_480 if not specified. VEO3 only supports RESOLUTION_720 and RESOLUTION_1080.
   */
  resolution?: CreateTextToVideoGenerationMotionString | null | undefined;
  /**
   * Apply a fixed seed to maintain consistency across generation sets. The maximum seed value is 2147483637 for Motion 2.0 and 4294967293 for Veo3.
   */
  seed?: number | null | undefined;
  /**
   * Predefined styles to enhance the prompt. This accepts a list of style uuids.
   */
  styleIds?: Array<string> | null | undefined;
  /**
   * Width of the output video
   */
  width?: number | null | undefined;
};

export type CreateTextToVideoGenerationMotionVideoGenerationOutput = {
  /**
   * API credits cost, available for Production API users.
   */
  apiCreditCost?: number | null | undefined;
  generationId?: string | undefined;
};

/**
 * Responses for POST /generations-text-to-video
 */
export type CreateTextToVideoGenerationResponseBody = {
  motionVideoGenerationJob?:
    | CreateTextToVideoGenerationMotionVideoGenerationOutput
    | null
    | undefined;
};

export type CreateTextToVideoGenerationResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for POST /generations-text-to-video
   */
  object?: CreateTextToVideoGenerationResponseBody | undefined;
};

/** @internal */
export const CreateTextToVideoGenerationString$inboundSchema: z.ZodNativeEnum<
  typeof CreateTextToVideoGenerationString
> = z.nativeEnum(CreateTextToVideoGenerationString);

/** @internal */
export const CreateTextToVideoGenerationString$outboundSchema: z.ZodNativeEnum<
  typeof CreateTextToVideoGenerationString
> = CreateTextToVideoGenerationString$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationString$ {
  /** @deprecated use `CreateTextToVideoGenerationString$inboundSchema` instead. */
  export const inboundSchema = CreateTextToVideoGenerationString$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationString$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationString$outboundSchema;
}

/** @internal */
export const CreateTextToVideoGenerationMotionString$inboundSchema:
  z.ZodNativeEnum<typeof CreateTextToVideoGenerationMotionString> = z
    .nativeEnum(CreateTextToVideoGenerationMotionString);

/** @internal */
export const CreateTextToVideoGenerationMotionString$outboundSchema:
  z.ZodNativeEnum<typeof CreateTextToVideoGenerationMotionString> =
    CreateTextToVideoGenerationMotionString$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationMotionString$ {
  /** @deprecated use `CreateTextToVideoGenerationMotionString$inboundSchema` instead. */
  export const inboundSchema =
    CreateTextToVideoGenerationMotionString$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationMotionString$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationMotionString$outboundSchema;
}

/** @internal */
export const CreateTextToVideoGenerationRequestBody$inboundSchema: z.ZodType<
  CreateTextToVideoGenerationRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  elements: z.nullable(z.array(shared.ElementInput$inboundSchema)).optional(),
  frameInterpolation: z.nullable(z.boolean()).optional(),
  height: z.nullable(z.number().int().default(480)),
  isPublic: z.nullable(z.boolean()).optional(),
  model: z.nullable(
    CreateTextToVideoGenerationString$inboundSchema.default(
      CreateTextToVideoGenerationString.Motion2,
    ),
  ),
  negativePrompt: z.nullable(z.string()).optional(),
  prompt: z.string(),
  promptEnhance: z.nullable(z.boolean()).optional(),
  promptEnhanceInstruction: z.nullable(z.string()).optional(),
  resolution: z.nullable(
    CreateTextToVideoGenerationMotionString$inboundSchema.default(
      CreateTextToVideoGenerationMotionString.Resolution480,
    ),
  ),
  seed: z.nullable(z.number().int()).optional(),
  styleIds: z.nullable(z.array(z.string())).optional(),
  width: z.nullable(z.number().int().default(832)),
});

/** @internal */
export type CreateTextToVideoGenerationRequestBody$Outbound = {
  elements?: Array<shared.ElementInput$Outbound> | null | undefined;
  frameInterpolation?: boolean | null | undefined;
  height: number | null;
  isPublic?: boolean | null | undefined;
  model: string | null;
  negativePrompt?: string | null | undefined;
  prompt: string;
  promptEnhance?: boolean | null | undefined;
  promptEnhanceInstruction?: string | null | undefined;
  resolution: string | null;
  seed?: number | null | undefined;
  styleIds?: Array<string> | null | undefined;
  width: number | null;
};

/** @internal */
export const CreateTextToVideoGenerationRequestBody$outboundSchema: z.ZodType<
  CreateTextToVideoGenerationRequestBody$Outbound,
  z.ZodTypeDef,
  CreateTextToVideoGenerationRequestBody
> = z.object({
  elements: z.nullable(z.array(shared.ElementInput$outboundSchema)).optional(),
  frameInterpolation: z.nullable(z.boolean()).optional(),
  height: z.nullable(z.number().int().default(480)),
  isPublic: z.nullable(z.boolean()).optional(),
  model: z.nullable(
    CreateTextToVideoGenerationString$outboundSchema.default(
      CreateTextToVideoGenerationString.Motion2,
    ),
  ),
  negativePrompt: z.nullable(z.string()).optional(),
  prompt: z.string(),
  promptEnhance: z.nullable(z.boolean()).optional(),
  promptEnhanceInstruction: z.nullable(z.string()).optional(),
  resolution: z.nullable(
    CreateTextToVideoGenerationMotionString$outboundSchema.default(
      CreateTextToVideoGenerationMotionString.Resolution480,
    ),
  ),
  seed: z.nullable(z.number().int()).optional(),
  styleIds: z.nullable(z.array(z.string())).optional(),
  width: z.nullable(z.number().int().default(832)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationRequestBody$ {
  /** @deprecated use `CreateTextToVideoGenerationRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    CreateTextToVideoGenerationRequestBody$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationRequestBody$outboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationRequestBody$Outbound` instead. */
  export type Outbound = CreateTextToVideoGenerationRequestBody$Outbound;
}

export function createTextToVideoGenerationRequestBodyToJSON(
  createTextToVideoGenerationRequestBody:
    CreateTextToVideoGenerationRequestBody,
): string {
  return JSON.stringify(
    CreateTextToVideoGenerationRequestBody$outboundSchema.parse(
      createTextToVideoGenerationRequestBody,
    ),
  );
}

export function createTextToVideoGenerationRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateTextToVideoGenerationRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateTextToVideoGenerationRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTextToVideoGenerationRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateTextToVideoGenerationMotionVideoGenerationOutput$inboundSchema:
  z.ZodType<
    CreateTextToVideoGenerationMotionVideoGenerationOutput,
    z.ZodTypeDef,
    unknown
  > = z.object({
    apiCreditCost: z.nullable(z.number().int()).optional(),
    generationId: z.string().optional(),
  });

/** @internal */
export type CreateTextToVideoGenerationMotionVideoGenerationOutput$Outbound = {
  apiCreditCost?: number | null | undefined;
  generationId?: string | undefined;
};

/** @internal */
export const CreateTextToVideoGenerationMotionVideoGenerationOutput$outboundSchema:
  z.ZodType<
    CreateTextToVideoGenerationMotionVideoGenerationOutput$Outbound,
    z.ZodTypeDef,
    CreateTextToVideoGenerationMotionVideoGenerationOutput
  > = z.object({
    apiCreditCost: z.nullable(z.number().int()).optional(),
    generationId: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationMotionVideoGenerationOutput$ {
  /** @deprecated use `CreateTextToVideoGenerationMotionVideoGenerationOutput$inboundSchema` instead. */
  export const inboundSchema =
    CreateTextToVideoGenerationMotionVideoGenerationOutput$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationMotionVideoGenerationOutput$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationMotionVideoGenerationOutput$outboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationMotionVideoGenerationOutput$Outbound` instead. */
  export type Outbound =
    CreateTextToVideoGenerationMotionVideoGenerationOutput$Outbound;
}

export function createTextToVideoGenerationMotionVideoGenerationOutputToJSON(
  createTextToVideoGenerationMotionVideoGenerationOutput:
    CreateTextToVideoGenerationMotionVideoGenerationOutput,
): string {
  return JSON.stringify(
    CreateTextToVideoGenerationMotionVideoGenerationOutput$outboundSchema.parse(
      createTextToVideoGenerationMotionVideoGenerationOutput,
    ),
  );
}

export function createTextToVideoGenerationMotionVideoGenerationOutputFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateTextToVideoGenerationMotionVideoGenerationOutput,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateTextToVideoGenerationMotionVideoGenerationOutput$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateTextToVideoGenerationMotionVideoGenerationOutput' from JSON`,
  );
}

/** @internal */
export const CreateTextToVideoGenerationResponseBody$inboundSchema: z.ZodType<
  CreateTextToVideoGenerationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  motionVideoGenerationJob: z.nullable(
    z.lazy(() =>
      CreateTextToVideoGenerationMotionVideoGenerationOutput$inboundSchema
    ),
  ).optional(),
});

/** @internal */
export type CreateTextToVideoGenerationResponseBody$Outbound = {
  motionVideoGenerationJob?:
    | CreateTextToVideoGenerationMotionVideoGenerationOutput$Outbound
    | null
    | undefined;
};

/** @internal */
export const CreateTextToVideoGenerationResponseBody$outboundSchema: z.ZodType<
  CreateTextToVideoGenerationResponseBody$Outbound,
  z.ZodTypeDef,
  CreateTextToVideoGenerationResponseBody
> = z.object({
  motionVideoGenerationJob: z.nullable(
    z.lazy(() =>
      CreateTextToVideoGenerationMotionVideoGenerationOutput$outboundSchema
    ),
  ).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationResponseBody$ {
  /** @deprecated use `CreateTextToVideoGenerationResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    CreateTextToVideoGenerationResponseBody$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationResponseBody$outboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationResponseBody$Outbound` instead. */
  export type Outbound = CreateTextToVideoGenerationResponseBody$Outbound;
}

export function createTextToVideoGenerationResponseBodyToJSON(
  createTextToVideoGenerationResponseBody:
    CreateTextToVideoGenerationResponseBody,
): string {
  return JSON.stringify(
    CreateTextToVideoGenerationResponseBody$outboundSchema.parse(
      createTextToVideoGenerationResponseBody,
    ),
  );
}

export function createTextToVideoGenerationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateTextToVideoGenerationResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateTextToVideoGenerationResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateTextToVideoGenerationResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateTextToVideoGenerationResponse$inboundSchema: z.ZodType<
  CreateTextToVideoGenerationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => CreateTextToVideoGenerationResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type CreateTextToVideoGenerationResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  object?: CreateTextToVideoGenerationResponseBody$Outbound | undefined;
};

/** @internal */
export const CreateTextToVideoGenerationResponse$outboundSchema: z.ZodType<
  CreateTextToVideoGenerationResponse$Outbound,
  z.ZodTypeDef,
  CreateTextToVideoGenerationResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  object: z.lazy(() => CreateTextToVideoGenerationResponseBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTextToVideoGenerationResponse$ {
  /** @deprecated use `CreateTextToVideoGenerationResponse$inboundSchema` instead. */
  export const inboundSchema =
    CreateTextToVideoGenerationResponse$inboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateTextToVideoGenerationResponse$outboundSchema;
  /** @deprecated use `CreateTextToVideoGenerationResponse$Outbound` instead. */
  export type Outbound = CreateTextToVideoGenerationResponse$Outbound;
}

export function createTextToVideoGenerationResponseToJSON(
  createTextToVideoGenerationResponse: CreateTextToVideoGenerationResponse,
): string {
  return JSON.stringify(
    CreateTextToVideoGenerationResponse$outboundSchema.parse(
      createTextToVideoGenerationResponse,
    ),
  );
}

export function createTextToVideoGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTextToVideoGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateTextToVideoGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTextToVideoGenerationResponse' from JSON`,
  );
}
