/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeleteDatasetByIdRequest extends SpeakeasyBase {
    /**
     * The ID of the dataset to delete.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

/**
 * columns and relationships of "datasets"
 */
export class DeleteDatasetByIdDatasets extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}

/**
 * Responses for DELETE /datasets/{id}
 */
export class DeleteDatasetByIdResponseBody extends SpeakeasyBase {
    /**
     * columns and relationships of "datasets"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delete_datasets_by_pk" })
    @Type(() => DeleteDatasetByIdDatasets)
    deleteDatasetsByPk?: DeleteDatasetByIdDatasets;
}

export class DeleteDatasetByIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Responses for DELETE /datasets/{id}
     */
    @SpeakeasyMetadata()
    object?: DeleteDatasetByIdResponseBody;
}
