/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteInitImageByIdRequest = {
  /**
   * _"id" is required_
   */
  id: string;
};

/**
 * columns and relationships of "init_images"
 */
export type InitImages = {
  id?: string | null | undefined;
};

/**
 * Responses for DELETE /init-image/{id}
 */
export type DeleteInitImageByIdResponseBody = {
  /**
   * columns and relationships of "init_images"
   */
  deleteInitImagesByPk?: InitImages | null | undefined;
};

export type DeleteInitImageByIdResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for DELETE /init-image/{id}
   */
  object?: DeleteInitImageByIdResponseBody | undefined;
};

/** @internal */
export type DeleteInitImageByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInitImageByIdRequest$outboundSchema: z.ZodType<
  DeleteInitImageByIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteInitImageByIdRequest
> = z.object({
  id: z.string(),
});

export function deleteInitImageByIdRequestToJSON(
  deleteInitImageByIdRequest: DeleteInitImageByIdRequest,
): string {
  return JSON.stringify(
    DeleteInitImageByIdRequest$outboundSchema.parse(deleteInitImageByIdRequest),
  );
}

/** @internal */
export const InitImages$inboundSchema: z.ZodType<
  InitImages,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
});

export function initImagesFromJSON(
  jsonString: string,
): SafeParseResult<InitImages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InitImages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InitImages' from JSON`,
  );
}

/** @internal */
export const DeleteInitImageByIdResponseBody$inboundSchema: z.ZodType<
  DeleteInitImageByIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  delete_init_images_by_pk: z.nullable(z.lazy(() => InitImages$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "delete_init_images_by_pk": "deleteInitImagesByPk",
  });
});

export function deleteInitImageByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteInitImageByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteInitImageByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteInitImageByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteInitImageByIdResponse$inboundSchema: z.ZodType<
  DeleteInitImageByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => DeleteInitImageByIdResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function deleteInitImageByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteInitImageByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteInitImageByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteInitImageByIdResponse' from JSON`,
  );
}
