/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeleteModelByIdRequest extends SpeakeasyBase {
    /**
     * The ID of the model to delete.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

/**
 * columns and relationships of "custom_models"
 */
export class CustomModels extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}

/**
 * Responses for DELETE /models/{id}
 */
export class DeleteModelByIdResponseBody extends SpeakeasyBase {
    /**
     * columns and relationships of "custom_models"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "delete_custom_models_by_pk" })
    @Type(() => CustomModels)
    deleteCustomModelsByPk?: CustomModels;
}

export class DeleteModelByIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Responses for DELETE /models/{id}
     */
    @SpeakeasyMetadata()
    object?: DeleteModelByIdResponseBody;
}
