/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class DeleteGenerationByIdRequest extends SpeakeasyBase {
  /**
   * The ID of the generation to delete.
   */
  @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
  id: string;
}

/**
 * columns and relationships of "generations"
 */
export class DeleteGenerationById200ApplicationJSONGenerations extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;
}

/**
 * Responses for DELETE /generations/{id}
 */
export class DeleteGenerationById200ApplicationJSON extends SpeakeasyBase {
  /**
   * columns and relationships of "generations"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "delete_generations_by_pk" })
  @Type(() => DeleteGenerationById200ApplicationJSONGenerations)
  deleteGenerationsByPk?: DeleteGenerationById200ApplicationJSONGenerations;
}

export class DeleteGenerationByIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Responses for DELETE /generations/{id}
   */
  @SpeakeasyMetadata()
  deleteGenerationById200ApplicationJSONObject?: DeleteGenerationById200ApplicationJSON;
}
