/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type DeleteInitImageByIdRequest = {
    /**
     * _"id" is required_
     */
    id: string;
};

/**
 * columns and relationships of "init_images"
 */
export type InitImages = {
    id?: string | null | undefined;
};

/**
 * Responses for DELETE /init-image/{id}
 */
export type DeleteInitImageByIdResponseBody = {
    /**
     * columns and relationships of "init_images"
     */
    deleteInitImagesByPk?: InitImages | null | undefined;
};

export type DeleteInitImageByIdResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Responses for DELETE /init-image/{id}
     */
    object?: DeleteInitImageByIdResponseBody | undefined;
};

/** @internal */
export namespace DeleteInitImageByIdRequest$ {
    export const inboundSchema: z.ZodType<DeleteInitImageByIdRequest, z.ZodTypeDef, unknown> =
        z.object({
            id: z.string(),
        });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteInitImageByIdRequest> =
        z.object({
            id: z.string(),
        });
}

/** @internal */
export namespace InitImages$ {
    export const inboundSchema: z.ZodType<InitImages, z.ZodTypeDef, unknown> = z.object({
        id: z.nullable(z.string()).optional(),
    });

    export type Outbound = {
        id?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InitImages> = z.object({
        id: z.nullable(z.string()).optional(),
    });
}

/** @internal */
export namespace DeleteInitImageByIdResponseBody$ {
    export const inboundSchema: z.ZodType<DeleteInitImageByIdResponseBody, z.ZodTypeDef, unknown> =
        z
            .object({
                delete_init_images_by_pk: z
                    .nullable(z.lazy(() => InitImages$.inboundSchema))
                    .optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    delete_init_images_by_pk: "deleteInitImagesByPk",
                });
            });

    export type Outbound = {
        delete_init_images_by_pk?: InitImages$.Outbound | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        DeleteInitImageByIdResponseBody
    > = z
        .object({
            deleteInitImagesByPk: z.nullable(z.lazy(() => InitImages$.outboundSchema)).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                deleteInitImagesByPk: "delete_init_images_by_pk",
            });
        });
}

/** @internal */
export namespace DeleteInitImageByIdResponse$ {
    export const inboundSchema: z.ZodType<DeleteInitImageByIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => DeleteInitImageByIdResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: DeleteInitImageByIdResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteInitImageByIdResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => DeleteInitImageByIdResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
