/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type Input = {
  /**
   * Optional list of collection IDs to add the generations to
   */
  collectionIds?: Array<number | null> | undefined;
  /**
   * Array of node input objects to customize the Blueprint
   */
  nodeInputs: Array<shared.NodeInput>;
  /**
   * Whether the resulting generations should be public
   */
  public: boolean;
};

export type ExecuteBlueprintRequestBody = {
  /**
   * The unique identifier of the Blueprint Version to execute
   */
  blueprintVersionId: string;
  input: Input;
};

/**
 * Bad Request - Invalid input type or missing required GraphQL field
 */
export type ExecuteBlueprintBlueprintsResponseBody = {
  /**
   * Error message describing the invalid input type or missing field
   */
  error?: string | undefined;
};

export type ExecuteBlueprint = {
  /**
   * The unique identifier of the Blueprint Execution
   */
  akUUID: string;
};

export type SuccessResponse = {
  executeBlueprint: ExecuteBlueprint;
};

/**
 * Responses for POST /blueprint-executions
 */
export type ExecuteBlueprintResponseBody =
  | SuccessResponse
  | Array<shared.ApiError>;

export type ExecuteBlueprintResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Bad Request - Invalid input type or missing required GraphQL field
   */
  object?: ExecuteBlueprintBlueprintsResponseBody | undefined;
  /**
   * Responses for POST /blueprint-executions
   */
  oneOf?: SuccessResponse | Array<shared.ApiError> | undefined;
};

/** @internal */
export type Input$Outbound = {
  collectionIds?: Array<number | null> | undefined;
  nodeInputs: Array<shared.NodeInput$Outbound>;
  public: boolean;
};

/** @internal */
export const Input$outboundSchema: z.ZodType<
  Input$Outbound,
  z.ZodTypeDef,
  Input
> = z.object({
  collectionIds: z.array(z.nullable(z.number().int())).optional(),
  nodeInputs: z.array(shared.NodeInput$outboundSchema),
  public: z.boolean(),
});

export function inputToJSON(input: Input): string {
  return JSON.stringify(Input$outboundSchema.parse(input));
}

/** @internal */
export type ExecuteBlueprintRequestBody$Outbound = {
  blueprintVersionId: string;
  input: Input$Outbound;
};

/** @internal */
export const ExecuteBlueprintRequestBody$outboundSchema: z.ZodType<
  ExecuteBlueprintRequestBody$Outbound,
  z.ZodTypeDef,
  ExecuteBlueprintRequestBody
> = z.object({
  blueprintVersionId: z.string(),
  input: z.lazy(() => Input$outboundSchema),
});

export function executeBlueprintRequestBodyToJSON(
  executeBlueprintRequestBody: ExecuteBlueprintRequestBody,
): string {
  return JSON.stringify(
    ExecuteBlueprintRequestBody$outboundSchema.parse(
      executeBlueprintRequestBody,
    ),
  );
}

/** @internal */
export const ExecuteBlueprintBlueprintsResponseBody$inboundSchema: z.ZodType<
  ExecuteBlueprintBlueprintsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
});

export function executeBlueprintBlueprintsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteBlueprintBlueprintsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExecuteBlueprintBlueprintsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteBlueprintBlueprintsResponseBody' from JSON`,
  );
}

/** @internal */
export const ExecuteBlueprint$inboundSchema: z.ZodType<
  ExecuteBlueprint,
  z.ZodTypeDef,
  unknown
> = z.object({
  akUUID: z.string(),
});

export function executeBlueprintFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteBlueprint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteBlueprint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteBlueprint' from JSON`,
  );
}

/** @internal */
export const SuccessResponse$inboundSchema: z.ZodType<
  SuccessResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  executeBlueprint: z.lazy(() => ExecuteBlueprint$inboundSchema),
});

export function successResponseFromJSON(
  jsonString: string,
): SafeParseResult<SuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuccessResponse' from JSON`,
  );
}

/** @internal */
export const ExecuteBlueprintResponseBody$inboundSchema: z.ZodType<
  ExecuteBlueprintResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SuccessResponse$inboundSchema),
  z.array(shared.ApiError$inboundSchema),
]);

export function executeBlueprintResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteBlueprintResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteBlueprintResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteBlueprintResponseBody' from JSON`,
  );
}

/** @internal */
export const ExecuteBlueprintResponse$inboundSchema: z.ZodType<
  ExecuteBlueprintResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => ExecuteBlueprintBlueprintsResponseBody$inboundSchema)
    .optional(),
  oneOf: z.union([
    z.lazy(() => SuccessResponse$inboundSchema),
    z.array(shared.ApiError$inboundSchema),
  ]).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function executeBlueprintResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteBlueprintResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteBlueprintResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteBlueprintResponse' from JSON`,
  );
}
