/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetBlueprintByIdRequest = {
  /**
   * The akUUID of the Blueprint to return
   */
  id: string;
};

export type GetBlueprintByIdSuccessResponse = {
  /**
   * A Blueprint object
   */
  blueprint?: shared.Blueprint | undefined;
};

/**
 * Successfully retrieved Blueprint
 */
export type GetBlueprintByIdResponseBody =
  | GetBlueprintByIdSuccessResponse
  | Array<shared.ApiError>;

export type GetBlueprintByIdResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successfully retrieved Blueprint
   */
  oneOf?: GetBlueprintByIdSuccessResponse | Array<shared.ApiError> | undefined;
};

/** @internal */
export type GetBlueprintByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetBlueprintByIdRequest$outboundSchema: z.ZodType<
  GetBlueprintByIdRequest$Outbound,
  z.ZodTypeDef,
  GetBlueprintByIdRequest
> = z.object({
  id: z.string(),
});

export function getBlueprintByIdRequestToJSON(
  getBlueprintByIdRequest: GetBlueprintByIdRequest,
): string {
  return JSON.stringify(
    GetBlueprintByIdRequest$outboundSchema.parse(getBlueprintByIdRequest),
  );
}

/** @internal */
export const GetBlueprintByIdSuccessResponse$inboundSchema: z.ZodType<
  GetBlueprintByIdSuccessResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  blueprint: shared.Blueprint$inboundSchema.optional(),
});

export function getBlueprintByIdSuccessResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBlueprintByIdSuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBlueprintByIdSuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBlueprintByIdSuccessResponse' from JSON`,
  );
}

/** @internal */
export const GetBlueprintByIdResponseBody$inboundSchema: z.ZodType<
  GetBlueprintByIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetBlueprintByIdSuccessResponse$inboundSchema),
  z.array(shared.ApiError$inboundSchema),
]);

export function getBlueprintByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetBlueprintByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBlueprintByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBlueprintByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetBlueprintByIdResponse$inboundSchema: z.ZodType<
  GetBlueprintByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  oneOf: z.union([
    z.lazy(() => GetBlueprintByIdSuccessResponse$inboundSchema),
    z.array(shared.ApiError$inboundSchema),
  ]).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getBlueprintByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBlueprintByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBlueprintByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBlueprintByIdResponse' from JSON`,
  );
}
