/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetCustomModelsByUserIdRequest = {
  /**
   * The ID of the user to return.
   */
  userId: string;
};

/**
 * columns and relationships of "custom_models"
 */
export type GetCustomModelsByUserIdCustomModels = {
  createdAt?: string | undefined;
  description?: string | undefined;
  id?: string | null | undefined;
  instancePrompt?: string | null | undefined;
  modelHeight?: number | undefined;
  modelWidth?: number | undefined;
  name?: string | undefined;
  public?: boolean | undefined;
  /**
   * The base version of stable diffusion to use if not using a custom model. v1_5 is 1.5, v2 is 2.1, if not specified it will default to v1_5. Also includes SDXL and SDXL Lightning models
   */
  sdVersion?: shared.SdVersions | undefined;
  /**
   * The status of the current task.
   */
  status?: shared.JobStatus | undefined;
  /**
   * The category the most accurately reflects the model.
   */
  type?: shared.CustomModelType | undefined;
  updatedAt?: string | undefined;
};

/**
 * Responses for GET /models/user/{userId}
 */
export type GetCustomModelsByUserIdResponseBody = {
  customModels?:
    | Array<GetCustomModelsByUserIdCustomModels | null>
    | null
    | undefined;
};

export type GetCustomModelsByUserIdResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for GET /models/user/{userId}
   */
  object?: GetCustomModelsByUserIdResponseBody | undefined;
};

/** @internal */
export type GetCustomModelsByUserIdRequest$Outbound = {
  userId: string;
};

/** @internal */
export const GetCustomModelsByUserIdRequest$outboundSchema: z.ZodType<
  GetCustomModelsByUserIdRequest$Outbound,
  z.ZodTypeDef,
  GetCustomModelsByUserIdRequest
> = z.object({
  userId: z.string(),
});

export function getCustomModelsByUserIdRequestToJSON(
  getCustomModelsByUserIdRequest: GetCustomModelsByUserIdRequest,
): string {
  return JSON.stringify(
    GetCustomModelsByUserIdRequest$outboundSchema.parse(
      getCustomModelsByUserIdRequest,
    ),
  );
}

/** @internal */
export const GetCustomModelsByUserIdCustomModels$inboundSchema: z.ZodType<
  GetCustomModelsByUserIdCustomModels,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().optional(),
  description: z.string().optional(),
  id: z.nullable(z.string()).optional(),
  instancePrompt: z.nullable(z.string()).optional(),
  modelHeight: z.number().int().optional(),
  modelWidth: z.number().int().optional(),
  name: z.string().optional(),
  public: z.boolean().optional(),
  sdVersion: shared.SdVersions$inboundSchema.optional(),
  status: shared.JobStatus$inboundSchema.optional(),
  type: shared.CustomModelType$inboundSchema.default(
    shared.CustomModelType.General,
  ),
  updatedAt: z.string().optional(),
});

export function getCustomModelsByUserIdCustomModelsFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomModelsByUserIdCustomModels, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustomModelsByUserIdCustomModels$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomModelsByUserIdCustomModels' from JSON`,
  );
}

/** @internal */
export const GetCustomModelsByUserIdResponseBody$inboundSchema: z.ZodType<
  GetCustomModelsByUserIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom_models: z.nullable(
    z.array(z.nullable(z.lazy(() =>
      GetCustomModelsByUserIdCustomModels$inboundSchema
    ))),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "custom_models": "customModels",
  });
});

export function getCustomModelsByUserIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomModelsByUserIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustomModelsByUserIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomModelsByUserIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetCustomModelsByUserIdResponse$inboundSchema: z.ZodType<
  GetCustomModelsByUserIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetCustomModelsByUserIdResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getCustomModelsByUserIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomModelsByUserIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomModelsByUserIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomModelsByUserIdResponse' from JSON`,
  );
}
