/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetInitImageByIdRequest extends SpeakeasyBase {
    /**
     * _"id" is required_
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id" })
    id: string;
}

/**
 * columns and relationships of "init_images"
 */
export class GetInitImageByIdInitImages extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url?: string;
}

/**
 * Responses for GET /init-image/{id}
 */
export class GetInitImageByIdResponseBody extends SpeakeasyBase {
    /**
     * columns and relationships of "init_images"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "init_images_by_pk" })
    @Type(() => GetInitImageByIdInitImages)
    initImagesByPk?: GetInitImageByIdInitImages;
}

export class GetInitImageByIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Responses for GET /init-image/{id}
     */
    @SpeakeasyMetadata()
    object?: GetInitImageByIdResponseBody;
}
