/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetMotionVariationByIdRequest = {
  /**
   * "id" is required
   */
  id: string;
};

/**
 * columns and relationships of "generated_image_variation_motion"
 */
export type GeneratedImageVariationMotion = {
  createdAt?: string | undefined;
  id?: string | null | undefined;
  /**
   * The type of motion variation.
   */
  motionTransformType?: shared.MotionVariationType | undefined;
  /**
   * The resolution of the upscaled video. RESOLUTION_720 is the only option for now.
   */
  resolution?: shared.MotionResolution | undefined;
  /**
   * The status of the current task.
   */
  status?: shared.JobStatus | undefined;
  url?: string | null | undefined;
};

/**
 * Responses for GET /motion-variations/{id}
 */
export type GetMotionVariationByIdResponseBody = {
  generatedImageVariationMotion?:
    | Array<GeneratedImageVariationMotion>
    | undefined;
};

export type GetMotionVariationByIdResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for GET /motion-variations/{id}
   */
  object?: GetMotionVariationByIdResponseBody | undefined;
};

/** @internal */
export type GetMotionVariationByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetMotionVariationByIdRequest$outboundSchema: z.ZodType<
  GetMotionVariationByIdRequest$Outbound,
  z.ZodTypeDef,
  GetMotionVariationByIdRequest
> = z.object({
  id: z.string(),
});

export function getMotionVariationByIdRequestToJSON(
  getMotionVariationByIdRequest: GetMotionVariationByIdRequest,
): string {
  return JSON.stringify(
    GetMotionVariationByIdRequest$outboundSchema.parse(
      getMotionVariationByIdRequest,
    ),
  );
}

/** @internal */
export const GeneratedImageVariationMotion$inboundSchema: z.ZodType<
  GeneratedImageVariationMotion,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().optional(),
  id: z.nullable(z.string()).optional(),
  motionTransformType: shared.MotionVariationType$inboundSchema.optional(),
  resolution: shared.MotionResolution$inboundSchema.optional(),
  status: shared.JobStatus$inboundSchema.optional(),
  url: z.nullable(z.string()).optional(),
});

export function generatedImageVariationMotionFromJSON(
  jsonString: string,
): SafeParseResult<GeneratedImageVariationMotion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GeneratedImageVariationMotion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GeneratedImageVariationMotion' from JSON`,
  );
}

/** @internal */
export const GetMotionVariationByIdResponseBody$inboundSchema: z.ZodType<
  GetMotionVariationByIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  generated_image_variation_motion: z.array(
    z.lazy(() => GeneratedImageVariationMotion$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "generated_image_variation_motion": "generatedImageVariationMotion",
  });
});

export function getMotionVariationByIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetMotionVariationByIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetMotionVariationByIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMotionVariationByIdResponseBody' from JSON`,
  );
}

/** @internal */
export const GetMotionVariationByIdResponse$inboundSchema: z.ZodType<
  GetMotionVariationByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => GetMotionVariationByIdResponseBody$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function getMotionVariationByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetMotionVariationByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMotionVariationByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMotionVariationByIdResponse' from JSON`,
  );
}
