/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * columns and relationships of "generated_images"
 */
export type ListPlatformModelsGeneratedImages = {
    id?: string | null | undefined;
    url?: string | undefined;
};

/**
 * columns and relationships of "custom_models"
 */
export type ListPlatformModelsCustomModels = {
    description?: string | undefined;
    featured?: boolean | undefined;
    /**
     * columns and relationships of "generated_images"
     */
    generatedImage?: ListPlatformModelsGeneratedImages | null | undefined;
    id?: string | null | undefined;
    name?: string | undefined;
    nsfw?: boolean | undefined;
};

/**
 * Responses for GET /api/rest/v1/platformModels
 */
export type ListPlatformModelsResponseBody = {
    customModels?: Array<ListPlatformModelsCustomModels> | undefined;
};

export type ListPlatformModelsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Responses for GET /api/rest/v1/platformModels
     */
    object?: ListPlatformModelsResponseBody | undefined;
};

/** @internal */
export namespace ListPlatformModelsGeneratedImages$ {
    export const inboundSchema: z.ZodType<
        ListPlatformModelsGeneratedImages,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            id: z.nullable(z.string()).optional(),
            url: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.url === undefined ? null : { url: v.url }),
            };
        });

    export type Outbound = {
        id?: string | null | undefined;
        url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ListPlatformModelsGeneratedImages
    > = z
        .object({
            id: z.nullable(z.string()).optional(),
            url: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.url === undefined ? null : { url: v.url }),
            };
        });
}

/** @internal */
export namespace ListPlatformModelsCustomModels$ {
    export const inboundSchema: z.ZodType<ListPlatformModelsCustomModels, z.ZodTypeDef, unknown> = z
        .object({
            description: z.string().optional(),
            featured: z.boolean().optional(),
            generated_image: z
                .nullable(z.lazy(() => ListPlatformModelsGeneratedImages$.inboundSchema))
                .optional(),
            id: z.nullable(z.string()).optional(),
            name: z.string().optional(),
            nsfw: z.boolean().optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.featured === undefined ? null : { featured: v.featured }),
                ...(v.generated_image === undefined ? null : { generatedImage: v.generated_image }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.nsfw === undefined ? null : { nsfw: v.nsfw }),
            };
        });

    export type Outbound = {
        description?: string | undefined;
        featured?: boolean | undefined;
        generated_image?: ListPlatformModelsGeneratedImages$.Outbound | null | undefined;
        id?: string | null | undefined;
        name?: string | undefined;
        nsfw?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlatformModelsCustomModels> =
        z
            .object({
                description: z.string().optional(),
                featured: z.boolean().optional(),
                generatedImage: z
                    .nullable(z.lazy(() => ListPlatformModelsGeneratedImages$.outboundSchema))
                    .optional(),
                id: z.nullable(z.string()).optional(),
                name: z.string().optional(),
                nsfw: z.boolean().optional(),
            })
            .transform((v) => {
                return {
                    ...(v.description === undefined ? null : { description: v.description }),
                    ...(v.featured === undefined ? null : { featured: v.featured }),
                    ...(v.generatedImage === undefined
                        ? null
                        : { generated_image: v.generatedImage }),
                    ...(v.id === undefined ? null : { id: v.id }),
                    ...(v.name === undefined ? null : { name: v.name }),
                    ...(v.nsfw === undefined ? null : { nsfw: v.nsfw }),
                };
            });
}

/** @internal */
export namespace ListPlatformModelsResponseBody$ {
    export const inboundSchema: z.ZodType<ListPlatformModelsResponseBody, z.ZodTypeDef, unknown> = z
        .object({
            custom_models: z
                .array(z.lazy(() => ListPlatformModelsCustomModels$.inboundSchema))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.custom_models === undefined ? null : { customModels: v.custom_models }),
            };
        });

    export type Outbound = {
        custom_models?: Array<ListPlatformModelsCustomModels$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlatformModelsResponseBody> =
        z
            .object({
                customModels: z
                    .array(z.lazy(() => ListPlatformModelsCustomModels$.outboundSchema))
                    .optional(),
            })
            .transform((v) => {
                return {
                    ...(v.customModels === undefined ? null : { custom_models: v.customModels }),
                };
            });
}

/** @internal */
export namespace ListPlatformModelsResponse$ {
    export const inboundSchema: z.ZodType<ListPlatformModelsResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => ListPlatformModelsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: ListPlatformModelsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListPlatformModelsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => ListPlatformModelsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
