/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Query parameters can also be provided in the request body as a JSON object
 */
export class PostGenerationsTextureRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "front_rotation_offset" })
    frontRotationOffset?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "modelAssetId" })
    modelAssetId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "negative_prompt" })
    negativePrompt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "preview" })
    preview?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "preview_direction" })
    previewDirection?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "prompt" })
    prompt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "sd_version" })
    sdVersion?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "seed" })
    seed?: number;
}

export class PostGenerationsTexture200ApplicationJSONTextureGenerationJobOutput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}

/**
 * Responses for POST /api/rest/v1/generations-texture
 */
export class PostGenerationsTexture200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "textureGenerationJob" })
    @Type(() => PostGenerationsTexture200ApplicationJSONTextureGenerationJobOutput)
    textureGenerationJob?: PostGenerationsTexture200ApplicationJSONTextureGenerationJobOutput;
}

export class PostGenerationsTextureResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Responses for POST /api/rest/v1/generations-texture
     */
    @SpeakeasyMetadata()
    postGenerationsTexture200ApplicationJSONObject?: PostGenerationsTexture200ApplicationJSON;
}
