/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

/**
 * Parameters for FANTASY_AVATAR_GENERATION service
 */
export type PricingCalculatorPricingCalculatorObject = {
  /**
   * The input height of the images. Must be between 32 and 1024 and be a multiple of 8. Note: Input resolution is not always the same as output resolution due to upscaling from other features
   */
  imageHeight?: number | undefined;
  /**
   * The input height of the images. Must be between 32 and 1024 and be a multiple of 8. Note: Input resolution is not always the same as output resolution due to upscaling from other features
   */
  imageWidth?: number | undefined;
  /**
   * The number of images to generate. Must be between 1 and 8. If either width or height is over 768, must be between 1 and 4.
   */
  numImages?: number | undefined;
};

/**
 * Parameters for IMAGE_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestObject = {
  /**
   * Enable to use Alchemy.
   */
  alchemyMode?: boolean | undefined;
  /**
   * The total cost of controlnets input.
   */
  controlnetsCost?: number | null | undefined;
  /**
   * Enable to use high resolution.
   */
  highResolution?: boolean | undefined;
  /**
   * The input height of the images. Must be between 32 and 1024 and be a multiple of 8. Note: Input resolution is not always the same as output resolution due to upscaling from other features
   */
  imageHeight?: number | undefined;
  /**
   * The input height of the images. Must be between 32 and 1024 and be a multiple of 8. Note: Input resolution is not always the same as output resolution due to upscaling from other features
   */
  imageWidth?: number | undefined;
  /**
   * The Step Count to use for the generation. Must be between 10 and 60.
   */
  inferenceSteps?: number | undefined;
  /**
   * Enable to use Flux Dev model.
   */
  isFluxDev?: boolean | null | undefined;
  /**
   * Enable to use Flux Kontext model.
   */
  isFluxKontext?: boolean | null | undefined;
  /**
   * Enable to use Flux Schnell model.
   */
  isFluxSchnell?: boolean | null | undefined;
  /**
   * Enable to use custom model.
   */
  isModelCustom?: boolean | null | undefined;
  /**
   * Enable to use Phoenix model.
   */
  isPhoenix?: boolean | null | undefined;
  /**
   * Enable to use SDXL model.
   */
  isSDXL?: boolean | null | undefined;
  /**
   * Enable to use SDXL Lightning model.
   */
  isSDXLLightning?: boolean | null | undefined;
  /**
   * Enable to use Ultra mode.
   */
  isUltra?: boolean | null | undefined;
  /**
   * The number of elements used for the generation.
   */
  loraCount?: number | null | undefined;
  /**
   * The number of images to generate. Must be between 1 and 8. If either width or height is over 768, must be between 1 and 4.
   */
  numImages?: number | undefined;
  /**
   * Enable to use PhotoReal. Requires enabling alchemy.
   */
  photoRealMode?: boolean | null | undefined;
  /**
   * Depth of field of photoReal. Must be 0.55 for low, 0.5 for medium, or 0.45 for high. Defaults to 0.55 if not specified.
   */
  photoRealStrength?: number | null | undefined;
  /**
   * The version of photoReal to use. Must be v1 or v2.
   */
  photoRealVersion?: string | null | undefined;
  /**
   * Enable to use Prompt Magic.
   */
  promptMagic?: boolean | null | undefined;
  /**
   * Strength of prompt magic. Must be a float between 0.1 and 1.0
   */
  promptMagicStrength?: number | null | undefined;
  /**
   * Prompt magic version v2 or v3, for use when promptMagic: true
   */
  promptMagicVersion?: string | null | undefined;
};

/**
 * Parameters for LCM_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyObject = {
  /**
   * The output height of the image. Must be 512, 640 or 1024.
   */
  height?: number | null | undefined;
  /**
   * Enable for instant upscale
   */
  instantRefine?: boolean | null | undefined;
  /**
   * Enable for normal alchemy upscale
   */
  refine?: boolean | null | undefined;
  /**
   * The output width of the image. Must be 512, 640 or 1024.
   */
  width?: number | null | undefined;
};

/**
 * The model for the training. Can be set to 'FLUX_DEV' for FLUX_DEV specific pricing or can be omitted.
 */
export enum SdVersion {
  FluxDev = "FLUX_DEV",
}

/**
 * Parameters for MODEL_TRAINING service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject =
  {
    /**
     * The number of images in the training dataset when sd_version is set to 'FLUX_DEV'. Must be between 1 and 50.
     */
    datasetImageCount?: number | null | undefined;
    /**
     * The resolution for training. Must be 512, 768, or 1024.
     */
    resolution?: number | undefined;
    /**
     * The model for the training. Can be set to 'FLUX_DEV' for FLUX_DEV specific pricing or can be omitted.
     */
    sdVersion?: SdVersion | null | undefined;
  };

/**
 * Parameters for MOTION_SVD_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject =
  {};

/**
 * Parameters for MOTION_VIDEO_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject =
  {
    /**
     * The resolution of the video. Must be RESOLUTION_480 or RESOLUTION_720.
     */
    resolution?: string | undefined;
  };

/**
 * Parameters for TEXTURE_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject =
  {
    preview?: boolean | undefined;
  };

/**
 * Parameters for UNIVERSAL_UPSCALER service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject =
  {
    /**
     * The maximum upscaled image size is 20 megapixels.
     */
    megapixel?: number | undefined;
  };

/**
 * Parameters for UNIVERSAL_UPSCALER_ULTRA service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject =
  {
    /**
     * The input height of the image.
     */
    inputHeight?: number | undefined;
    /**
     * The input width of the image.
     */
    inputWidth?: number | undefined;
    /**
     * The upscale multiplier of the universal upscaler. Must be between 1.00 and 2.00.
     */
    upscaleMultiplier?: number | undefined;
  };

/**
 * The resolution of the video. Supported resolution for VEO3 is RESOLUTION_720.
 */
export enum PricingCalculatorString {
  Resolution720 = "RESOLUTION_720",
}

/**
 * Parameters for VEO3_MOTION_VIDEO_GENERATION service
 */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject =
  {
    /**
     * The resolution of the video. Supported resolution for VEO3 is RESOLUTION_720.
     */
    resolution?: PricingCalculatorString | undefined;
  };

/**
 * Parameters for the service
 */
export type PricingCalculatorObject = {
  /**
   * Parameters for FANTASY_AVATAR_GENERATION service
   */
  fantasyAvatarGeneration?:
    | PricingCalculatorPricingCalculatorObject
    | null
    | undefined;
  /**
   * Parameters for IMAGE_GENERATION service
   */
  imageGeneration?:
    | PricingCalculatorPricingCalculatorRequestObject
    | null
    | undefined;
  /**
   * Parameters for LCM_GENERATION service
   */
  lcmGeneration?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyObject
    | null
    | undefined;
  /**
   * Parameters for MODEL_TRAINING service
   */
  modelTraining?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject
    | null
    | undefined;
  /**
   * Parameters for MOTION_SVD_GENERATION service
   */
  motionSvdGeneration?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject
    | null
    | undefined;
  /**
   * Parameters for MOTION_VIDEO_GENERATION service
   */
  motionVideoGeneration?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject
    | null
    | undefined;
  /**
   * Parameters for TEXTURE_GENERATION service
   */
  textureGeneration?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject
    | null
    | undefined;
  /**
   * Parameters for UNIVERSAL_UPSCALER service
   */
  universalUpscaler?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject
    | null
    | undefined;
  /**
   * Parameters for UNIVERSAL_UPSCALER_ULTRA service
   */
  universalUpscalerUltra?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject
    | null
    | undefined;
  /**
   * Parameters for VEO3_MOTION_VIDEO_GENERATION service
   */
  veo3MotionVideoGeneration?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject
    | null
    | undefined;
};

export type PricingCalculatorRequestBody = {
  /**
   * The services to be chosen for calculating the API credit cost.
   */
  service?: shared.PricingCalculatorServices | undefined;
  /**
   * Parameters for the service
   */
  serviceParams?: PricingCalculatorObject | undefined;
};

export type CalculateProductionApiServiceCost = {
  /**
   * API service cost to generate the image.
   */
  cost?: number | undefined;
};

/**
 * Responses for POST /pricing-calculator
 */
export type PricingCalculatorResponseBody = {
  calculateProductionApiServiceCost?:
    | CalculateProductionApiServiceCost
    | null
    | undefined;
};

export type PricingCalculatorResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for POST /pricing-calculator
   */
  object?: PricingCalculatorResponseBody | undefined;
};

/** @internal */
export type PricingCalculatorPricingCalculatorObject$Outbound = {
  imageHeight?: number | undefined;
  imageWidth?: number | undefined;
  numImages?: number | undefined;
};

/** @internal */
export const PricingCalculatorPricingCalculatorObject$outboundSchema: z.ZodType<
  PricingCalculatorPricingCalculatorObject$Outbound,
  z.ZodTypeDef,
  PricingCalculatorPricingCalculatorObject
> = z.object({
  imageHeight: z.number().int().optional(),
  imageWidth: z.number().int().optional(),
  numImages: z.number().int().optional(),
});

export function pricingCalculatorPricingCalculatorObjectToJSON(
  pricingCalculatorPricingCalculatorObject:
    PricingCalculatorPricingCalculatorObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorObject$outboundSchema.parse(
      pricingCalculatorPricingCalculatorObject,
    ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestObject$Outbound = {
  alchemyMode?: boolean | undefined;
  controlnetsCost?: number | null | undefined;
  highResolution?: boolean | undefined;
  imageHeight?: number | undefined;
  imageWidth?: number | undefined;
  inferenceSteps?: number | undefined;
  isFluxDev?: boolean | null | undefined;
  isFluxKontext?: boolean | null | undefined;
  isFluxSchnell?: boolean | null | undefined;
  isModelCustom?: boolean | null | undefined;
  isPhoenix?: boolean | null | undefined;
  isSDXL?: boolean | null | undefined;
  isSDXLLightning?: boolean | null | undefined;
  isUltra?: boolean | null | undefined;
  loraCount?: number | null | undefined;
  numImages?: number | undefined;
  photoRealMode?: boolean | null | undefined;
  photoRealStrength?: number | null | undefined;
  photoRealVersion?: string | null | undefined;
  promptMagic?: boolean | null | undefined;
  promptMagicStrength?: number | null | undefined;
  promptMagicVersion?: string | null | undefined;
};

/** @internal */
export const PricingCalculatorPricingCalculatorRequestObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestObject
  > = z.object({
    alchemyMode: z.boolean().optional(),
    controlnetsCost: z.nullable(z.number().int()).optional(),
    highResolution: z.boolean().optional(),
    imageHeight: z.number().int().optional(),
    imageWidth: z.number().int().optional(),
    inferenceSteps: z.number().int().optional(),
    isFluxDev: z.nullable(z.boolean()).optional(),
    isFluxKontext: z.nullable(z.boolean()).optional(),
    isFluxSchnell: z.nullable(z.boolean()).optional(),
    isModelCustom: z.nullable(z.boolean()).optional(),
    isPhoenix: z.nullable(z.boolean()).optional(),
    isSDXL: z.nullable(z.boolean()).optional(),
    isSDXLLightning: z.nullable(z.boolean()).optional(),
    isUltra: z.nullable(z.boolean()).optional(),
    loraCount: z.nullable(z.number().int()).optional(),
    numImages: z.number().int().optional(),
    photoRealMode: z.nullable(z.boolean()).optional(),
    photoRealStrength: z.nullable(z.number()).optional(),
    photoRealVersion: z.nullable(z.string()).optional(),
    promptMagic: z.nullable(z.boolean()).optional(),
    promptMagicStrength: z.nullable(z.number()).optional(),
    promptMagicVersion: z.nullable(z.string()).optional(),
  });

export function pricingCalculatorPricingCalculatorRequestObjectToJSON(
  pricingCalculatorPricingCalculatorRequestObject:
    PricingCalculatorPricingCalculatorRequestObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestObject$outboundSchema.parse(
      pricingCalculatorPricingCalculatorRequestObject,
    ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyObject$Outbound =
  {
    height?: number | null | undefined;
    instantRefine?: boolean | null | undefined;
    refine?: boolean | null | undefined;
    width?: number | null | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyObject
  > = z.object({
    height: z.nullable(z.number().int()).optional(),
    instantRefine: z.nullable(z.boolean()).optional(),
    refine: z.nullable(z.boolean()).optional(),
    width: z.nullable(z.number().int()).optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyObject$outboundSchema
      .parse(pricingCalculatorPricingCalculatorRequestRequestBodyObject),
  );
}

/** @internal */
export const SdVersion$outboundSchema: z.ZodNativeEnum<typeof SdVersion> = z
  .nativeEnum(SdVersion);

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$Outbound =
  {
    datasetImageCount?: number | null | undefined;
    resolution?: number | undefined;
    sd_version?: string | null | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject
  > = z.object({
    datasetImageCount: z.nullable(z.number().int()).optional(),
    resolution: z.number().int().optional(),
    sdVersion: z.nullable(SdVersion$outboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      sdVersion: "sd_version",
    });
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$Outbound =
  {};

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject
  > = z.object({});

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$Outbound =
  {
    resolution?: string | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject
  > = z.object({
    resolution: z.string().optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$Outbound =
  {
    preview?: boolean | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject
  > = z.object({
    preview: z.boolean().optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$Outbound =
  {
    megapixel?: number | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject
  > = z.object({
    megapixel: z.number().int().optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$Outbound =
  {
    inputHeight?: number | undefined;
    inputWidth?: number | undefined;
    upscaleMultiplier?: number | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject
  > = z.object({
    inputHeight: z.number().int().optional(),
    inputWidth: z.number().int().optional(),
    upscaleMultiplier: z.number().optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject,
      ),
  );
}

/** @internal */
export const PricingCalculatorString$outboundSchema: z.ZodNativeEnum<
  typeof PricingCalculatorString
> = z.nativeEnum(PricingCalculatorString);

/** @internal */
export type PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$Outbound =
  {
    resolution?: string | undefined;
  };

/** @internal */
export const PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$outboundSchema:
  z.ZodType<
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$Outbound,
    z.ZodTypeDef,
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject
  > = z.object({
    resolution: PricingCalculatorString$outboundSchema.optional(),
  });

export function pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObjectToJSON(
  pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject:
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject,
): string {
  return JSON.stringify(
    PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$outboundSchema
      .parse(
        pricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject,
      ),
  );
}

/** @internal */
export type PricingCalculatorObject$Outbound = {
  FANTASY_AVATAR_GENERATION?:
    | PricingCalculatorPricingCalculatorObject$Outbound
    | null
    | undefined;
  IMAGE_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestObject$Outbound
    | null
    | undefined;
  LCM_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyObject$Outbound
    | null
    | undefined;
  MODEL_TRAINING?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$Outbound
    | null
    | undefined;
  MOTION_SVD_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$Outbound
    | null
    | undefined;
  MOTION_VIDEO_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$Outbound
    | null
    | undefined;
  TEXTURE_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$Outbound
    | null
    | undefined;
  UNIVERSAL_UPSCALER?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$Outbound
    | null
    | undefined;
  UNIVERSAL_UPSCALER_ULTRA?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$Outbound
    | null
    | undefined;
  VEO3_MOTION_VIDEO_GENERATION?:
    | PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$Outbound
    | null
    | undefined;
};

/** @internal */
export const PricingCalculatorObject$outboundSchema: z.ZodType<
  PricingCalculatorObject$Outbound,
  z.ZodTypeDef,
  PricingCalculatorObject
> = z.object({
  fantasyAvatarGeneration: z.nullable(
    z.lazy(() => PricingCalculatorPricingCalculatorObject$outboundSchema),
  ).optional(),
  imageGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestObject$outboundSchema
    ),
  ).optional(),
  lcmGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyObject$outboundSchema
    ),
  ).optional(),
  modelTraining: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsObject$outboundSchema
    ),
  ).optional(),
  motionSvdGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONSVDGENERATIONObject$outboundSchema
    ),
  ).optional(),
  motionVideoGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsMOTIONVIDEOGENERATIONObject$outboundSchema
    ),
  ).optional(),
  textureGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsTEXTUREGENERATIONObject$outboundSchema
    ),
  ).optional(),
  universalUpscaler: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERObject$outboundSchema
    ),
  ).optional(),
  universalUpscalerUltra: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsUNIVERSALUPSCALERULTRAObject$outboundSchema
    ),
  ).optional(),
  veo3MotionVideoGeneration: z.nullable(
    z.lazy(() =>
      PricingCalculatorPricingCalculatorRequestRequestBodyServiceParamsVeo3MOTIONVIDEOGENERATIONObject$outboundSchema
    ),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    fantasyAvatarGeneration: "FANTASY_AVATAR_GENERATION",
    imageGeneration: "IMAGE_GENERATION",
    lcmGeneration: "LCM_GENERATION",
    modelTraining: "MODEL_TRAINING",
    motionSvdGeneration: "MOTION_SVD_GENERATION",
    motionVideoGeneration: "MOTION_VIDEO_GENERATION",
    textureGeneration: "TEXTURE_GENERATION",
    universalUpscaler: "UNIVERSAL_UPSCALER",
    universalUpscalerUltra: "UNIVERSAL_UPSCALER_ULTRA",
    veo3MotionVideoGeneration: "VEO3_MOTION_VIDEO_GENERATION",
  });
});

export function pricingCalculatorObjectToJSON(
  pricingCalculatorObject: PricingCalculatorObject,
): string {
  return JSON.stringify(
    PricingCalculatorObject$outboundSchema.parse(pricingCalculatorObject),
  );
}

/** @internal */
export type PricingCalculatorRequestBody$Outbound = {
  service?: string | undefined;
  serviceParams?: PricingCalculatorObject$Outbound | undefined;
};

/** @internal */
export const PricingCalculatorRequestBody$outboundSchema: z.ZodType<
  PricingCalculatorRequestBody$Outbound,
  z.ZodTypeDef,
  PricingCalculatorRequestBody
> = z.object({
  service: shared.PricingCalculatorServices$outboundSchema.optional(),
  serviceParams: z.lazy(() => PricingCalculatorObject$outboundSchema)
    .optional(),
});

export function pricingCalculatorRequestBodyToJSON(
  pricingCalculatorRequestBody: PricingCalculatorRequestBody,
): string {
  return JSON.stringify(
    PricingCalculatorRequestBody$outboundSchema.parse(
      pricingCalculatorRequestBody,
    ),
  );
}

/** @internal */
export const CalculateProductionApiServiceCost$inboundSchema: z.ZodType<
  CalculateProductionApiServiceCost,
  z.ZodTypeDef,
  unknown
> = z.object({
  cost: z.number().int().optional(),
});

export function calculateProductionApiServiceCostFromJSON(
  jsonString: string,
): SafeParseResult<CalculateProductionApiServiceCost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CalculateProductionApiServiceCost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CalculateProductionApiServiceCost' from JSON`,
  );
}

/** @internal */
export const PricingCalculatorResponseBody$inboundSchema: z.ZodType<
  PricingCalculatorResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  calculateProductionApiServiceCost: z.nullable(
    z.lazy(() => CalculateProductionApiServiceCost$inboundSchema),
  ).optional(),
});

export function pricingCalculatorResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PricingCalculatorResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PricingCalculatorResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PricingCalculatorResponseBody' from JSON`,
  );
}

/** @internal */
export const PricingCalculatorResponse$inboundSchema: z.ZodType<
  PricingCalculatorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => PricingCalculatorResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function pricingCalculatorResponseFromJSON(
  jsonString: string,
): SafeParseResult<PricingCalculatorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PricingCalculatorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PricingCalculatorResponse' from JSON`,
  );
}
