/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Query parameters can also be provided in the request body as a JSON object
 */
export type UploadModelAssetRequestBody = {
  modelExtension?: string | undefined;
  name?: string | null | undefined;
};

export type ModelAssetUploadOutput = {
  modelFields?: string | null | undefined;
  modelId?: string | null | undefined;
  modelKey?: string | null | undefined;
  modelUrl?: string | null | undefined;
};

/**
 * Responses for POST /api/rest/v1/models-3d/upload
 */
export type UploadModelAssetResponseBody = {
  uploadModelAsset?: ModelAssetUploadOutput | null | undefined;
};

export type UploadModelAssetResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Responses for POST /api/rest/v1/models-3d/upload
   */
  object?: UploadModelAssetResponseBody | undefined;
};

/** @internal */
export type UploadModelAssetRequestBody$Outbound = {
  modelExtension?: string | undefined;
  name?: string | null | undefined;
};

/** @internal */
export const UploadModelAssetRequestBody$outboundSchema: z.ZodType<
  UploadModelAssetRequestBody$Outbound,
  z.ZodTypeDef,
  UploadModelAssetRequestBody
> = z.object({
  modelExtension: z.string().optional(),
  name: z.nullable(z.string()).optional(),
});

export function uploadModelAssetRequestBodyToJSON(
  uploadModelAssetRequestBody: UploadModelAssetRequestBody,
): string {
  return JSON.stringify(
    UploadModelAssetRequestBody$outboundSchema.parse(
      uploadModelAssetRequestBody,
    ),
  );
}

/** @internal */
export const ModelAssetUploadOutput$inboundSchema: z.ZodType<
  ModelAssetUploadOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  modelFields: z.nullable(z.string()).optional(),
  modelId: z.nullable(z.string()).optional(),
  modelKey: z.nullable(z.string()).optional(),
  modelUrl: z.nullable(z.string()).optional(),
});

export function modelAssetUploadOutputFromJSON(
  jsonString: string,
): SafeParseResult<ModelAssetUploadOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelAssetUploadOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelAssetUploadOutput' from JSON`,
  );
}

/** @internal */
export const UploadModelAssetResponseBody$inboundSchema: z.ZodType<
  UploadModelAssetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uploadModelAsset: z.nullable(
    z.lazy(() => ModelAssetUploadOutput$inboundSchema),
  ).optional(),
});

export function uploadModelAssetResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UploadModelAssetResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadModelAssetResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadModelAssetResponseBody' from JSON`,
  );
}

/** @internal */
export const UploadModelAssetResponse$inboundSchema: z.ZodType<
  UploadModelAssetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  object: z.lazy(() => UploadModelAssetResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function uploadModelAssetResponseFromJSON(
  jsonString: string,
): SafeParseResult<UploadModelAssetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadModelAssetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadModelAssetResponse' from JSON`,
  );
}
