/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { motionCreateImageToVideoGeneration } from "../funcs/motionCreateImageToVideoGeneration.js";
import { motionCreateTextToVideoGeneration } from "../funcs/motionCreateTextToVideoGeneration.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Motion extends ClientSDK {
  /**
   * Create a video generation from an image
   *
   * @remarks
   * This endpoint will generate a video using an uploaded or generated image.
   */
  async createImageToVideoGeneration(
    request?: operations.CreateImageToVideoGenerationRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateImageToVideoGenerationResponse> {
    return unwrapAsync(motionCreateImageToVideoGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a video generation from a text prompt
   *
   * @remarks
   * This endpoint will generate a video using a text prompt
   */
  async createTextToVideoGeneration(
    request?: operations.CreateTextToVideoGenerationRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateTextToVideoGenerationResponse> {
    return unwrapAsync(motionCreateTextToVideoGeneration(
      this,
      request,
      options,
    ));
  }
}
