workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api-docs-nine-delta.vercel.app/cloud/openapi.json
targets:
    leonardo-ts-sdk:
        target: typescript
        source: my-source
        output: ./
        publish:
            npm:
                token: $NPM_TOKEN
