/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as fs from "fs";

export function recordTest(id: string) {
  fs.appendFileSync("test-typescript-record.txt", id + "\n");
}
